[package]
name = "cami"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "4"
flate2 = "1.0"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
tar = "0.4"
regex = "1"
